### ISSUE TITLE
Incompatible with `pytest-timeout`

### ISSUE THREAD

**Issue by basnijholt** [CodSpeedHQ/pytest-codspeed#59]
In https://github.com/pipefunc/pipefunc/pull/459 I am trying to add `pytest-timeout`, however, just having it loaded as a plugin will result in the error below:

```
INTERNALERROR> Traceback (most recent call last):
  INTERNALERROR>   File "/home/runner/micromamba/envs/pipefunc/lib/python3.12/site-packages/pytest_codspeed/instruments/valgrind/_wrapper/__init__.py", line 11, in get_lib
  INTERNALERROR>     from .dist_callgrind_wrapper import lib  # type: ignore
  INTERNALERROR>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  INTERNALERROR> ModuleNotFoundError: No module named 'pytest_codspeed.instruments.valgrind._wrapper.dist_callgrind_wrapper'
  INTERNALERROR> 
  INTERNALERROR> The above exception was the direct cause of the following exception:
  INTERNALERROR> 
  INTERNALERROR> Traceback (most recent call last):
  INTERNALERROR>   File "/home/runner/micromamba/envs/pipefunc/lib/python3.12/site-packages/_pytest/main.py", line 2[79](https://github.com/pipefunc/pipefunc/actions/runs/12363199054/job/34504057265?pr=459#step:6:82), in wrap_session
  INTERNALERROR>     config._do_configure()
  INTERNALERROR>   File "/home/runner/micromamba/envs/pipefunc/lib/python3.12/site-packages/_pytest/config/__init__.py", line 1118, in _do_configure
  INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
  INTERNALERROR>   File "/home/runner/micromamba/envs/pipefunc/lib/python3.12/site-packages/pluggy/_hooks.py", line 535, in call_historic
  INTERNALERROR>     res = self._hookexec(self.name, self._hookimpls.copy(), kwargs, False)
  INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  INTERNALERROR>   File "/home/runner/micromamba/envs/pipefunc/lib/python3.12/site-packages/pluggy/_manager.py", line 120, in _hookexec
  INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  INTERNALERROR>   File "/home/runner/micromamba/envs/pipefunc/lib/python3.12/site-packages/pluggy/_callers.py", line 139, in _multicall
  INTERNALERROR>     raise exception.with_traceback(exception.__traceback__)
  INTERNALERROR>   File "/home/runner/micromamba/envs/pipefunc/lib/python3.12/site-packages/pluggy/_callers.py", line 103, in _multicall
  INTERNALERROR>     res = hook_impl.function(*args)
  INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^^^^
  INTERNALERROR>   File "/home/runner/micromamba/envs/pipefunc/lib/python3.12/site-packages/pytest_codspeed/plugin.py", line 166, in pytest_configure
  INTERNALERROR>     instrument=instrument(codspeedconfig),
  INTERNALERROR>                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  INTERNALERROR>   File "/home/runner/micromamba/envs/pipefunc/lib/python3.12/site-packages/pytest_codspeed/instruments/valgrind/__init__.py", line 31, in __init__
  INTERNALERROR>     self.lib = get_lib()
  INTERNALERROR>                ^^^^^^^^^
  INTERNALERROR>   File "/home/runner/micromamba/envs/pipefunc/lib/python3.12/site-packages/pytest_codspeed/instruments/valgrind/_wrapper/__init__.py", line 15, in get_lib
  INTERNALERROR>     raise Exception("Failed to get a compiled wrapper") from e
  INTERNALERROR> Exception: Failed to get a compiled wrapper
```

Taken from build log https://github.com/pipefunc/pipefunc/actions/runs/12363234683/job/34504160607.

I cannot reproduce this locally on my MacOS machine but it happens consistently in GitHub Actions runners.

**Comment by basnijholt** [comment]
Turns out I was just installing a faulty version of the conda package that didn't have the newest version compiled correctly.

This fixes that https://github.com/conda-forge/pytest-codspeed-feedstock/pull/5.
